
home:
  hero:
    name: Ego.
    intro: #Nothing
    avatar: <svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 48 48"><circle cx="24" cy="24" r="21.5" fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round"></circle><path fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round" d="m32 16l-4 16l-4-16l-4 16l-4-16"></path></svg>
  posts: recommend

articles:
  path: 'posts'
  per_page: 10
  order_by: -date

menu:
  - name: Posts
    url: /posts/
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: Archives
    url: /archives/

socialLink:
  - name: Github
    link: https://github.com/Yw37153

friends:
  - name: 
    avatar: 
    link: 
    desc: 

#works:
#  - name: 文逸行
#    desc: 
#    tags:
#    link: Yw37153.github.io
#    cover: <svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 48 48"><circle cx="24" cy="24" r="21.5" fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round"></circle><path fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round" d="m32 16l-4 16l-4-16l-4 16l-4-16"></path></svg>

footer:
  builtUpTime: 2025-10-24 16:58:42

favicon: <svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 48 48"><circle cx="24" cy="24" r="21.5" fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round"></circle><path fill="none" stroke="#1b79a1" stroke-linecap="round" stroke-linejoin="round" d="m32 16l-4 16l-4-16l-4 16l-4-16"></path></svg>

comment:
  enable: true
  type: giscus

search:
  enable: true
  type: pagefind

giscus:
  repo: https://github.com/Yw37153/Yw37153.github.io
  repoid: R_kgDOQISfjg
  category: General
  categoryid: DIC_kwDOQISfjs4C0iEL
  mapping: pathname
  strict: "0"
  reactionsenabled: "1"
  emitmetadata: "0"
  inputposition: bottom
  loading: lazy